y = y-1
idle_spr = spr_nakoling;
walk_spr = spr_nakoling_walk;
jump_spr = spr_nakoling_jump
sleepy_spr = spr_nakoling_sleep
Target = obj_azure
destinationX = x
destinationY = y
TargetX = destinationX
TargetY = destinationY
check_my_self = 1;
path = path_add()
xspd = 0;
yspd = 0;
grav = .275;
max_grav = 4
jspd = 5
spd = 2
should_jump = 0;
y_ground = room_height
make_unstuck = 0;

pit_check_range = 30 //pit_check_depth+ (pit_check_depth/2)
pit_check_depth = 20
jump_range = jspd*15
fall_range = spd*50
detect_range = 120
timer_rescout = 300;
can_jump = 1

state = "Wandering"
sub_state = "Scouting"